django/lecture3/hello/urls.py
from django.urls import path
from . import views
urlpatterns = [  
    path("", views.index, name="index"),
    path("<str:name>",views.greet, name="greet"),
    path("susmi",views.susmi,name="susmi"),
    path("david", views.david, name="david")

]

django/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('tasks/', include("tasks.urls")),
    path('newyear/',include("newyear.urls"))
]

django/lecture3/newyear/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.index, name="index")
]

django/lecture3/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("",views.index,name="index"),
    path("add",views.add, name="add")
]

django/lecture3/newyear/models.py
from django.db import models

# Create your models here.

django/lecture3/tasks/models.py
from django.db import models

# Create your models here.

django/lecture3/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def susmi(request):
    return HttpResponse("Hello, Susmi!")
def david(request):
    return HttpResponse("Hello, David")
def greet(request,name):
    return render(request, "hello/greet.html", {
        "name":name.capitalize()
    })

django/lecture3/newyear/views.py
from django.shortcuts import render
import datetime


def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": True
    })

django/lecture3/tasks/views.py
from django.shortcuts import render

tasks = ["foo","bar","baz"]
# Create your views here.
def index(request):
    return render(request,"tasks/index.html",{
        "tasks": tasks
    })
def add(request):
    return render(request, "tasks/add.html")

django/lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello, {{ name }}!</h1>
    </body>
</html>

django/lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello, world!</h1>
    </body>
</html>

django/lecture3/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Is it New Year's?</title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}

    </body>
</html>

django/lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layouts.html" %}
{% block body %}
    <h1>Add</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        <input type="text" name="tasks">
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

django/lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layouts.html" %}
{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}

    </ul>
    <a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}

django/lecture3/tasks/templates/tasks/layouts.html
<!DOCTYPE html>
<html lang="en">
    <head>

    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>